// Login actions
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SERVER_RESPONSE_SUCCESS =
  "LOGIN_USER_SERVER_RESPONSE_SUCCESS";
export const LOGIN_USER_SERVER_RESPONSE_ERROR =
  "LOGIN_USER_SERVER_RESPONSE_ERROR";

// Google login actions
export const GOOGLE_LOGIN_USER = "GOOGLE_LOGIN_USER";
export const GOOGLE_LOGIN_USER_SERVER_RESPONSE_SUCCESS =
  "GOOGLE_LOGIN_USER_SERVER_RESPONSE_SUCCESS";
export const GOOGLE_LOGIN_USER_SERVER_RESPONSE_ERROR =
  "GOOGLE_LOGIN_USER_SERVER_RESPONSE_ERROR";

// sign up actions
export const SIGNUP_USER = "SIGNUP_USER";
export const SIGNUP_USER_SERVER_RESPONSE_SUCCESS =
  "SIGNUP_USER_SERVER_RESPONSE_SUCCESS";
export const SIGNUP_USER_SERVER_RESPONSE_ERROR =
  "SIGNUP_USER_SERVER_RESPONSE_ERROR";

// Images
export const GET_DEFAULT_IMAGES = "GET_DEFAULT_IMAGES";
export const GET_DEFAULT_IMAGES_SERVER_RESPONSE_SUCCESS =
  "GET_DEFAULT_IMAGES_SERVER_RESPONSE_SUCCESS";
export const GET_DEFAULT_IMAGES_SERVER_RESPONSE_ERROR =
  "GET_DEFAULT_IMAGES_SERVER_RESPONSE_ERROR";

// server actions
export const SERVER_CALL_FAILED = "SERVER_CALL_FAILED";
